openapi: 3.0.1
info:
  title: PaymentLCM
  description: API Definition of PaymentLCM
  version: 1.0.0
servers:
- url: http://localhost:8290/payments
paths:
  /submit/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
